### ISSUE TITLE
Move off reach-ui

### ISSUE THREAD

**Issue by NickyMeuleman** [NickyMeuleman/nicky-blog#165]
https://github.com/reach/reach-ui/issues/972

Specifically @reach/tabs and @reach/tooltip

Edit: I want to make clear @chaance is awesome.
(And he's the reason for my blogposts have that `<details>` element to the side btw, still love that)

**Comment by NickyMeuleman** [comment]
alternative: do nothing and wait until @reach/tabs is React 18 compatible
https://github.com/reach/reach-ui/issues/972#issuecomment-1275497222

**Comment by chaance** [comment]
FWIW I do think I'm close on getting `descendants` working for React 18, which is the only holdup for Tabs. Tooltip is *probably* fine, but we do some DOM manipulation in effects that concerns me considering StrictMode will run those effects twice. I think those are also *probably* fine, they just need a good review when I have time.

**Comment by NickyMeuleman** [comment]
closing all issues before complete rewrite
