### ISSUE TITLE
White page problem

### ISSUE THREAD

**Issue by 2u841r** [NickyMeuleman/nicky-blog#186]
I went to the homepage and clicked on a blog post. Then, I tried to navigate using the "Uses" option in the navigation menu . But all I got was a blank page! (which also applies to the homepage, from any page- browsers top left sides back button).
After refreshing, the page finally displayed properly.

I tested this across multiple browsers.

**Comment by NickyMeuleman** [comment]
Thanks for noticing and reporting this, and my apologies for noticing this message so late.
I tried to fix this, and ran into a dependency problem.

The more permanent "fix" will be:
I'm going to completely rewrite this site from the ground up.
